import type { Category } from './types';

export const MAIN_CATEGORIES: Category[] = [
  { category_id: 0, slug: 'home', name: 'Home', icon: '🏠', isGroup: false, order_index: 0 },
  { category_id: 1, slug: 'world', name: 'World', icon: '🌍', isGroup: true, order_index: 1 },
  { category_id: 14, slug: 'counties', name: 'Counties', icon: '🏢', isGroup: true, order_index: 2 },
  { category_id: 15, slug: 'politics', name: 'Politics', icon: '🏛️', isGroup: true, order_index: 3 },
  { category_id: 16, slug: 'business', name: 'Business', icon: '💼', isGroup: true, order_index: 4 },
  { category_id: 17, slug: 'opinion', name: 'Opinion', icon: '💭', isGroup: true, order_index: 5 },
  { category_id: 18, slug: 'sports', name: 'Sports', icon: '⚽', isGroup: true, order_index: 6 },
  { category_id: 19, slug: 'lifestyle', name: 'Life & Style', icon: '🎭', isGroup: true, order_index: 7 },
  { category_id: 20, slug: 'entertainment', name: 'Entertainment', icon: '🎉', isGroup: true, order_index: 8 },
  { category_id: 21, slug: 'tech', name: 'Technology', icon: '💻', isGroup: true, order_index: 9 },
  { category_id: 22, slug: 'other', name: 'Other', icon: '📌', isGroup: true, order_index: 10 }
];

export const CATEGORY_ICONS: { [key: string]: string } = {
  'home': '🏠',
  'world': '🌍',
  'national': '🇰🇪',
  'east-africa': '🌍',
  'africa': '🌍',
  'international': '🌍',
  'live': '🔴',
  'world-reports': '📊',
  'counties': '🏢',
  'nairobi': '🏙️',
  'coast': '🏖️',
  'mountain': '⛰️',
  'lake-region': '🌊',
  'rift-valley': '🏞️',
  'northern': '🧭',
  'eastern': '🌅',
  'western': '🌄',
  'county-reports': '📋',
  'politics': '🏛️',
  'governance': '⚖️',
  'legal': '⚖️',
  'elections': '🗳️',
  'parliament': '🏛️',
  'political-reports': '📑',
  'politics-others': '📄',
  'business': '💼',
  'companies': '🏢',
  'finance-markets': '📈',
  'investment': '💰',
  'enterprise': '🤝',
  'economy': '📊',
  'banking': '🏦',
  'business-reports': '📊',
  'opinion': '💭',
  'editorials': '✏️',
  'columnists': '👤',
  'bloggers': '📝',
  'letters': '✉️',
  'trail-blazing': '🔥',
  'ai-graphics': '🤖',
  'analysis': '🔬',
  'sports': '⚽',
  'football': '⚽',
  'athletics': '🏃',
  'rugby': '🏉',
  'motorsport': '🏎️',
  'sports-vybe': '💬',
  'cricket': '🏏',
  'basketball': '🏀',
  'other-sports': '🏆',
  'sports-others': '⚾',
  'lifestyle': '🎭',
  'motoring': '🚗',
  'culture': '🎨',
  'family': '👨‍👩‍👧‍👦',
  'relationships': '💑',
  'travel': '✈️',
  'wellness': '🧘',
  'fashion': '👗',
  'food': '🍴',
  'lifestyle-others': '✨',
  'entertainment': '🎉',
  'buzz': '🔔',
  'trending': '🔥',
  'trending-pics': '📸',
  'gossip': '💬',
  'life-stories': '📖',
  'music': '🎵',
  'movies': '🎬',
  'celebrity': '⭐',
  'entertainment-others': '🎪',
  'tech': '💻',
  'technology': '💻',
  'innovations': '💡',
  'gadgets': '📱',
  'startups': '🚀',
  'digital-life': '📡',
  'ai': '🤖',
  'mobile': '📱',
  'gaming': '🎮',
  'tech-reports': '📱',
  'tech-others': '⚙️',
  'other': '📌',
  'human-rights': '✊',
  'climate-crisis': '🌱',
  'investigations': '🔍',
  'interactives': '🎛️',
  'features': '📑',
  'in-pictures': '📷',
  'special-reports': '📋',
};

export const CATEGORY_COLORS: { [key: string]: string } = {
  'world': '#2563eb',
  'national': '#c0392b',
  'east-africa': '#e67e22',
  'africa': '#f39c12',
  'international': '#3498db',
  'live': '#ff6b6b',
  'world-reports': '#34495e',
  'counties': '#3498db',
  'nairobi': '#3498db',
  'coast': '#16a085',
  'mountain': '#8e44ad',
  'lake-region': '#2980b9',
  'rift-valley': '#d35400',
  'northern': '#c0392b',
  'eastern': '#f39c12',
  'western': '#27ae60',
  'county-reports': '#34495e',
  'politics': '#e74c3c',
  'governance': '#7f8c8d',
  'legal': '#34495e',
  'elections': '#e74c3c',
  'parliament': '#9b59b6',
  'political-reports': '#34495e',
  'politics-others': '#95a5a6',
  'business': '#2ecc71',
  'companies': '#2ecc71',
  'finance-markets': '#27ae60',
  'investment': '#d4af37',
  'enterprise': '#16a085',
  'economy': '#1abc9c',
  'banking': '#2c3e50',
  'business-reports': '#34495e',
  'opinion': '#9b59b6',
  'editorials': '#9b59b6',
  'columnists': '#8e44ad',
  'bloggers': '#e67e22',
  'letters': '#2980b9',
  'trail-blazing': '#e74c3c',
  'ai-graphics': '#f39c12',
  'analysis': '#34495e',
  'sports': '#f39c12',
  'football': '#2ecc71',
  'athletics': '#f39c12',
  'rugby': '#e74c3c',
  'motorsport': '#e67e22',
  'sports-vybe': '#0891b2',
  'cricket': '#16a085',
  'basketball': '#e91e63',
  'other-sports': '#9b59b6',
  'sports-others': '#95a5a6',
  'lifestyle': '#e91e63',
  'motoring': '#34495e',
  'culture': '#9b59b6',
  'family': '#e91e63',
  'relationships': '#e74c3c',
  'travel': '#3498db',
  'wellness': '#2ecc71',
  'fashion': '#e91e63',
  'food': '#f39c12',
  'lifestyle-others': '#95a5a6',
  'entertainment': '#ff6b6b',
  'buzz': '#e91e63',
  'trending': '#ff6b6b',
  'trending-pics': '#ff6b6b',
  'gossip': '#e74c3c',
  'life-stories': '#9b59b6',
  'music': '#3498db',
  'movies': '#e67e22',
  'celebrity': '#f39c12',
  'entertainment-others': '#95a5a6',
  'tech': '#1abc9c',
  'technology': '#1abc9c',
  'innovations': '#1abc9c',
  'gadgets': '#3498db',
  'startups': '#2ecc71',
  'digital-life': '#9b59b6',
  'ai': '#e74c3c',
  'mobile': '#f39c12',
  'gaming': '#e91e63',
  'tech-reports': '#34495e',
  'tech-others': '#95a5a6',
  'other': '#34495e',
  'human-rights': '#e74c3c',
  'climate-crisis': '#16a085',
  'investigations': '#8e44ad',
  'interactives': '#3498db',
  'features': '#f39c12',
  'in-pictures': '#e67e22',
  'special-reports': '#34495e',
};

export const GROUP_TO_CATEGORY_MAP: { [key: string]: string } = {
  'World': 'world',
  'Counties': 'counties',
  'Politics': 'politics',
  'Business': 'business',
  'Opinion': 'opinion',
  'Sports': 'sports',
  'Life & Style': 'lifestyle',
  'Entertainment': 'entertainment',
  'Technology': 'tech',
  'Other': 'other',
};

export const CATEGORY_GROUPS: Record<string, string[]> = {
  'world': ['national', 'east-africa', 'africa', 'international', 'live', 'world-reports'],
  'counties': ['nairobi', 'coast', 'mountain', 'lake-region', 'rift-valley', 'northern', 'eastern', 'western', 'county-reports'],
  'politics': ['governance', 'legal', 'elections', 'parliament', 'political-reports', 'politics-others'],
  'business': ['companies', 'finance-markets', 'investment', 'enterprise', 'economy', 'banking', 'business-reports'],
  'opinion': ['editorials', 'columnists', 'bloggers', 'letters', 'trail-blazing', 'ai-graphics', 'analysis'],
  'sports': ['football', 'athletics', 'rugby', 'motorsport', 'sports-vybe', 'cricket', 'basketball', 'other-sports', 'sports-others'],
  'lifestyle': ['motoring', 'culture', 'family', 'relationships', 'travel', 'wellness', 'fashion', 'food', 'lifestyle-others'],
  'entertainment': ['buzz', 'trending', 'trending-pics', 'gossip', 'life-stories', 'music', 'movies', 'celebrity', 'entertainment-others'],
  'tech': ['innovations', 'gadgets', 'startups', 'digital-life', 'ai', 'mobile', 'gaming', 'tech-reports', 'tech-others'],
  'other': ['human-rights', 'climate-crisis', 'investigations', 'interactives', 'features', 'in-pictures', 'special-reports']
};